//{ Vegetable Merchant
	ACTION_IF FILE_EXISTS_IN_GAME ~SC#HubJ.dlg~ THEN BEGIN
		PRINT @40 /* ~Hubelpot the Vegetable Merchant mod detected. Updating dialogs accordingly...~*/ 
		SILENT
		COMPILE ~%MOD_FOLDER%/compat/veg/d/xaldsoa.d~ USING ~%MOD_FOLDER%/compat/veg/tra/english/xaldveg.tra~
		COMPILE ~%MOD_FOLDER%/compat/veg/d/xaldtob.d~ USING ~%MOD_FOLDER%/compat/veg/tra/english/xaldveg.tra~
	END
//}