//{ If the player dies without a phylactery, game over. 
IF
	Race(Player1, LICH)
	TriggerOverride(Player1, GlobalLT("XA_LD_LichDestroyed", "LOCALS", 1))
	OR(2)
		StateCheck(Player1, STATE_DEAD)
		StateCheck(Player1, STATE_REALLY_DEAD)
	OR(2)
		TriggerOverride(Player1, GlobalLT("XA_LD_HasPhylactery", "LOCALS", 1))
		TriggerOverride(Player1, Global("XA_LD_PhylacteryBroken", "LOCALS", 1))
THEN
	RESPONSE #100
		ReallyForceSpellRES("xalddest", Player1)
		GameOver(19377)
END
//}
