//{ Saradas Magic
	ACTION_IF FILE_EXISTS_IN_GAME ~!SarJ.dlg~ THEN BEGIN
		PRINT @46 /* ~Saradas Magic NPC mod detected. Updating dialogs accordingly...~ */ 
		SILENT
		COMPILE ~%MOD_FOLDER%/compat/saradas/d/xaldsoa.d~ USING ~%MOD_FOLDER%/compat/saradas/tra/english/xaldsara.tra~
		COMPILE ~%MOD_FOLDER%/compat/saradas/d/xaldtob.d~ USING ~%MOD_FOLDER%/compat/saradas/tra/english/xaldsara.tra~
	END 
//}