IF
	GlobalLT("XA_LD_MorrisSpawned", "AR5000", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		CreateCreature("XALDGD2", [1100.1020], S)
		SetGlobal("XA_LD_MorrisSpawned", "AR5000", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF
	Global("XA_LD_MorrisSpawned", "AR5000", 1)
	GlobalLT("XA_LD_MorrisKilledInSaradush", "AR5000", 1)
	!InMyArea("XALDGD2")
THEN
	RESPONSE #100
		SetGlobal("XA_LD_JournalEntry_5", "GLOBAL", 1)
		SetGlobal("XA_LD_MorrisKilledInSaradush", "AR5000", 1)
		Continue()
END
