// Athkatla Combat Script

IF
	PickPocketFailed([ANYONE])
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		DisplayStringHead(Myself, @0) // ~I despise your thievery. Goodbye.~ [xald1114]
		SetInterrupt(TRUE)
		Continue()
END

IF
	OR(3)
		See(NearestEnemyOf(Myself))
		AttackedBy([ANYONE], DEFAULT)
		PickPocketFailed([ANYONE])
THEN
	RESPONSE #100
		SetGlobal("XA_LD_MorrisDD800", "GLOBAL", 1)
		ReallyForceSpellRES("OHBTELWE",Myself)
END