PRINT @63 /* ~Processing Lichdom Assistant...~ */
SILENT

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/assistant/baf~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/assistant/d~

ACTION_IF FILE_EXISTS_IN_GAME ~BALDUR.BCS~ THEN BEGIN
	EXTEND_BOTTOM ~BALDUR.BCS~ ~%MOD_FOLDER%/assistant/baf/xaldasst.baf~
	PRINT @61
	SILENT
END

ACTION_IF FILE_EXISTS_IN_GAME ~BDBALDUR.BCS~ THEN BEGIN
	EXTEND_BOTTOM ~BDBALDUR.BCS~ ~%MOD_FOLDER%/assistant/baf/xaldasst.baf~
	PRINT @64
	SILENT
END

ACTION_IF FILE_EXISTS_IN_GAME ~BALDUR25.BCS~ THEN BEGIN
	EXTEND_BOTTOM ~BALDUR25.BCS~ ~%MOD_FOLDER%/assistant/baf/xaldasst.baf~
	PRINT @62
	SILENT
END

//{ bam
	COPY ~%MOD_FOLDER%/assistant/bam/xaldasst.bam~ ~override~
//}

//{ cre
	COPY ~%MOD_FOLDER%/assistant/cre/xalddbg.cre~ ~override~
	SAY NAME1 @7/* ~Lichdom Assistant~ */
	SAY NAME2 @7/* ~Lichdom Assistant~*/
	
//}

//{ spl
	COPY ~%MOD_FOLDER%/assistant/spl/xaldasst.spl~ ~override~
	SAY NAME1 @7/* ~Lichdom Assistant~ */
	SAY NAME2 @7/* ~Lichdom Assistant~*/
//}
